apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nubi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nubi
    app.kubernetes.io/part-of: nubi
  name: nubiz0wm
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: nubi
    weight: 100
status: {}
