apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nubi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nubi
    app.kubernetes.io/part-of: nubi
  name: nubi
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: nubi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: nubi
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/brianwcook-tenant/nubi/nubi@sha256:a915634344ce678521bbb7a8d22ffc88ef09de86869bb96162b963a0a694b0a9
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
