apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nubi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nubi
    app.kubernetes.io/part-of: nubi
  name: nubi
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: nubi
status:
  loadBalancer: {}
